name: Go Package Workflow
on:
  workflow_dispatch:
jobs:
  ci-workflow:
    name: ci-workflow
    runs-on: ubuntu-latest
    steps:
      - run: calebtraceyco/devops/templates/.github/workflows/go-test.yml
      - run: calebtraceyco/devops/templates/.github/workflows/go-lint.yml
      - run: calebtraceyco/devops/templates/.github/workflows/codeql.yml
