name: Go Package Workflow
on:
  workflow_dispatch:
jobs:
  ci-workflow:
    strategy:
      matrix:
        go-version: [ 1.20.2 ]
        os: [ ubuntu-latest ]
    name: Go Test (Go ${{ matrix.go-version }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - run: calebtraceyco/devops/.github/workflows/go-test.yml
      - run: calebtraceyco/devops/.github/workflows/go-lint.yml
      - run: calebtraceyco/devops/.github/workflows/codeql.yml
