name: Build
runs:
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: 1.20.x
#        cache: true
    - uses: actions/checkout@v3
    - run: go build ./...
