name: go-lint
jobs:
  lint:
    name: Go Lint
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.2
          cache: false
      - uses: actions/checkout@v3
      - name: Go Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52
