name: Go Package Workflow
on:
  workflow_call:
jobs:
  test:
    uses: ./templates/.github/workflows/go-test.yml
  lint:
    uses: ./templates/.github/workflows/go-lint.yml
  analyze:
    uses: ./templates/.github/workflows/codeql.yml
