name: Go Package Workflow
on:
  workflow_call:
jobs:
  test:
    uses: calebtraceyco/devops/templates/.github/workflows/go-test.yml@main
  lint:
    uses: calebtraceyco/devops/templates/.github/workflows/go-lint.yml@main
  analyze:
    uses: calebtraceyco/devops/templates/.github/workflows/codeql.yml@main
