name: Go Package Workflow
on:
  push:
    branches:
      - MYB-*
      - main
  pull_request:
    branches:
      - main
  workflow_call:
jobs:
  test:
    uses: workflows/go-test.yml
  lint:
    uses: workflows/go-lint.yml
  analyze:
    uses: workflows/codeql.yml
