name: Go Package Workflow
on:
  workflow_call:
jobs:
  test:
    uses: calebtraceyco/devops/.github/templates/go-test.yml
  lint:
    uses: calebtraceyco/devops/.github/templates/go-lint.yml
  analyze:
    uses: calebtraceyco/devops/.github/templates/codeql.yml
