name: Go Package Workflow
on:
  workflow_call:
jobs:
  test:
    uses: calebtraceyco/devops/.github/workflows/templates/go-test.yml@main
  lint:
    uses: calebtraceyco/devops/.github/workflows/templates/go-lint.yml@main
  analyze:
    uses: calebtraceyco/devops/.github/workflows/templates/codeql.yml@main
