name: Go Package Workflow
on:
  workflow_call:
jobs:
  ci-workflow:
    name: ci-workflow
    runs-on: ubuntu-latest
    steps:
      - run: ../templates/go-test.yml
      - run: ../templates/go-lint.yml
      - run: ../templates/codeql.yml
