name: Test

runs:
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - uses: actions/setup-go@v4
      with:
        go-version: 1.20.x
    - name: Run coverage
      run: go test -race -coverprofile=coverage.out -covermode=atomic ./...
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
